Bulky/BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using BulkyBook.Models;
using Microsoft.AspNetCore.Authorization;
using BulkyBook.Utility;
using BulkyBook.DataAccess.Repository.IRepository;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _uniteOfWork;

        public CompanyController(IUnitOfWork unitOfWork )
        {
            _uniteOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            var Companys = _uniteOfWork.Company.GetAll().ToList();
            return View(Companys);
        }

        public IActionResult Upsert(int? id)
        {
            if(id == null || id == 0)
            {
                return View(new Company());
            }
            else
            {
                Company company = _uniteOfWork.Company.Get(u => u.Id == id);
                return View(company);
            }
        }
        [HttpPost]
        public IActionResult Upsert(Company company  )
        {
            if (ModelState.IsValid)
            {
                if(company.Id == 0)
                {
                    _uniteOfWork.Company.Add(company);
                }
                else
                {
                    _uniteOfWork.Company.Update(company);
                }
                _uniteOfWork.Save();
                TempData["success"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(company);
            }
            
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> obj = _uniteOfWork.Company.GetAll().ToList();
            return Json(new { data = obj });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _uniteOfWork.Company.Get(u => u.Id == id);

            if (obj == null)
            {
                return Json(new { successs = false, message = "Error while deleting" });
            }

            _uniteOfWork.Company.Remove(obj);
            _uniteOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

Bulky/BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class ProductController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork , IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var objProductList = _unitOfWork.Product.GetAll(includeProperties:"Category").ToList();
            
            return View(objProductList);
        }

        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                CatgoryList = _unitOfWork.Category
				.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString()
				}),
                Product = new Product()
            };
            if(id == null || id == 0)
            {
                return View(productVM);
            }
            else
            {
                //Update
                productVM.Product = _unitOfWork.Product.Get(u => u.Id == id , includeProperties: "Images");
				return View(productVM);
			}
		}
        [HttpPost]
        public IActionResult Upsert(ProductVM obj , List<IFormFile>? files )
        {
            if (ModelState.IsValid)
            {
				if (obj.Product.Id == 0 || obj.Product.Id == null)
				{
					_unitOfWork.Product.Add(obj.Product);
				}
				else
				{
					_unitOfWork.Product.Update(obj.Product);
				}

				_unitOfWork.Save();


				string wwwRootPath = _webHostEnvironment.WebRootPath;
                if(files != null)
                {
                    foreach (var item in files)
                    {
						string filename = Guid.NewGuid().ToString() + Path.GetExtension(item.FileName);
                        string productPath = @"images\products\product-" + obj.Product.Id;
						string finalPath = Path.Combine(wwwRootPath, productPath);
                        if(!Directory.Exists(finalPath))
                        {
                            Directory.CreateDirectory(finalPath);
                        }
                        using (var fileStream = new FileStream(Path.Combine(finalPath, filename), FileMode.Create))
                        {
                            item.CopyTo(fileStream);
                        }

                        ProductImage productImage = new()
                        {
                            ImageUrl = @"\" + productPath + @"\" + filename,
                            ProductId = obj.Product.Id
                        };

                        if(obj.Product.Images == null)
                        {
                            obj.Product.Images = new List<ProductImage>();
                        }

                        obj.Product.Images.Add(productImage);
                    }


                    _unitOfWork.Product.Update(obj.Product);
                    _unitOfWork.Save();
					
				}

                
                TempData["Sucess"] = "Product Created / Updated Successfully";
                return RedirectToAction("Index");
            }
            else
            {
                obj.CatgoryList = _unitOfWork.Category
                .GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
				return View(obj);
			}
        }

        public IActionResult DeleteImage(int imageId)
        {
            var imageToBeDeleted = _unitOfWork.ProductImage.Get(u => u.Id == imageId);
            int productid = imageToBeDeleted.ProductId;
            if(imageToBeDeleted != null)
            {
                if (!string.IsNullOrEmpty(imageToBeDeleted.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, imageToBeDeleted.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork.ProductImage.Remove(imageToBeDeleted);
                _unitOfWork.Save();

                TempData["success"] = "Delted successfully";
			}
            return RedirectToAction(nameof(Upsert) , new { id = productid});
        }

		#region API CALLS

		[HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = objProductList });
        }
        
		[HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Product.Get(u => u.Id == id);

            if(obj == null)
            {
                return Json(new { successs = false, message = "Error while deleting"  });
            }

			//string productPath = @"images\products\product\" + id;

			//var  oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
			//if (System.IO.File.Exists(oldImagePath))
			//{
			//	System.IO.File.Delete(oldImagePath);
			//}

			string productPath = @"images\products\product-" + id;
			string finalPath = Path.Combine(_webHostEnvironment.WebRootPath, productPath);
			if (Directory.Exists(finalPath))
			{
                string[] filePaths = Directory.GetFiles(finalPath);
                foreach (string filePath in filePaths)
                {
                    System.IO.File.Delete(filePath);
				}
                Directory.Delete(finalPath);
			}
			_unitOfWork.Product.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }
		#endregion
	}
}

Bulky/BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 mt-4 momo">
	<div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Edit Company</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">

		<div class="container">
			<div class="row  pb-3">
				<div class="col-6">
				</div>
				<div class="col-6 text-end">
					<a asp-area="Admin" asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
						<i class="bi bi-cloud-plus"></i>   Add New Company
					</a>
				</div>
			</div>

			<table id="tblData" class="table table-bordered table-striped" width="100%">
				<thead>
					<tr>
						<th>
							 Name
						</th>
						<th>
							Address
						</th>
						<th>
							City
						</th>
						<th>
							State
						</th>
						<th>
							Postal Code
						</th>
						<th>Phone Number</th>
					</tr>
				</thead>
@* 				<tbody>
					@foreach (var item in Model)
					{
						<tr>@item.Name</tr>
						<tr>@item.StreetAddress</tr>
						<tr>@item.City</tr>
						<tr>@item.State</tr>
						<tr>@item.PostalCode</tr>
						<tr>@item.PhoneNumber</tr>
					}
				</tbody> *@
			</table>

		</div>

	</div>
</div>

@section Scripts{
	<script src="/js/Company.js"></script>
}

Bulky/BulkyWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 mt-4 momo">
	<div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">@(Model.Id != 0 ? "Update" : "Create") Company</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<input asp-for="Id" hidden />
			<div class="row">
				<div class="col-12">
					<div class="border p-3 mt-4">


						@* <div asp-validation-summary="ModelOnly"></div> *@
						@* //////////////////////////////////////////////////// *@
						<div class="mb-3 row p-1">
							<label asp-for="Name" class="p-0"></label>
							<input asp-for="Name" class="form-control" />
							<span asp-validation-for="Name" class="text-danger"></span>
						</div>
						<div class="mb-3 row p-1">
							<label asp-for="PhoneNumber" class="p-0"></label>
							<input asp-for="PhoneNumber" class="form-control" />
							<span asp-validation-for="PhoneNumber" class="text-danger"></span>
						</div>
						<div class="mb-3 row p-1">
							<label asp-for="StreetAddress" class="p-0"></label>
							<input asp-for="StreetAddress" class="form-control" />
							<span asp-validation-for="StreetAddress" class="text-danger"></span>
						</div>
						<div class="mb-3 row p-1">
							<label asp-for="City" class="p-0"></label>
							<input asp-for="City" class="form-control" />
							<span asp-validation-for="City" class="text-danger"></span>
						</div>
						<div class="mb-3 row p-1">
							<label asp-for="State" class="p-0"></label>
							<input asp-for="State" class="form-control" />
							<span asp-validation-for="State" class="text-danger"></span>
						</div>
						<div class="mb-3 row p-1">
							<label asp-for="PostalCode" class="p-0"></label>
							<input asp-for="PostalCode" class="form-control" />
							<span asp-validation-for="PostalCode" class="text-danger"></span>
						</div>
						

						@* //////////////////////////////////////////////////////////// *@

						<div class="row">
							<div class="col-6 col-mid-3">
								@if (Model.Id != 0)
								{
									<button type="submit" class="btn btn-primary form-control">Update</button>
								}
								else
								{
									<button type="submit" class="btn btn-primary form-control">Create</button>
								}
							</div>
							<div class="col-6 col-mid-3">
								<a asp-controller="Product" asp-action="Index" class="btn btn-secondary border form-control"> Back To List </a>
							</div>
						</div>

					</div>
				</div>
			</div>

		</form>
	</div>
</div>



@section Scripts
{
	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'anchor autolink charmap codesample emoticons   lists  searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage advtemplate ai mentions tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss markdown',
			toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
			tinycomments_mode: 'embedded',
			tinycomments_author: 'Author name',
			mergetags_list: [
				{ value: 'First.Name', title: 'First Name' },
				{ value: 'Email', title: 'Email' },
			],
			ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
		});
	</script>
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}